name: whiskit_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

Flutter: ">=1.10.0"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.3.2+2

  firebase_core: "^0.5.0"
  firebase_auth: "^0.18.0+1"
  firebase_storage: "^4.0.0"

  cloud_firestore: ^0.14.0+2
  country_icons: ^1.1.1
  url_launcher: ^5.6.0
  flutter_twitter_login:
    git:
      url: git://github.com/eudangeld/flutter_twitter_login.git
  shared_preferences: ^0.5.10
  image_picker: ^0.6.7+11
  image_cropper: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

